### ISSUE TITLE
几个翻译问题

### ISSUE THREAD

**Issue by albertlee** [Scratch3Lab/codelab-mindstorms#10]
1972年 - 出现了 SmallTalk。这是 Alan Kay 的心血结晶，谁创造的术语“面向对象”。

who ，这里不应该翻译成“谁”，而应该是 “他”

----
To eval a program list, control is passed to the first object and the remainder is treated as its message.
为了评估程序列表，控制权被传递给第一个对象，剩余部分被视为其消息。

eval  应为 求值

**Comment by AngelKitty** [comment]
@albertlee 哦哦，是这样子，非常感谢您指出错误。

**Comment by AngelKitty** [comment]
@wwj718 这个issue也可以关了
