### ISSUE TITLE
认领 《Dynamicland, seeing spaces, and design studio》 http://vitor.io/on-dynamicland 

### ISSUE THREAD

**Issue by wangshub** [Scratch3Lab/codelab-mindstorms#5]
@wwj718

**Comment by wwj718** [comment]
@wangshub  可能得以CodeLab的名义跟http://vitor.io打个招呼，申请授权，文章似乎不是以CC协议发布。

**Comment by wangshub** [comment]
@wwj718 抱歉，忘了看协议了 😭，那可能 codelab 域名的邮箱会好一点

**Comment by wangshub** [comment]
> To the extent possible under law, Vitorio Miliano has waived all copyright and related or neighboring rights to “Dynamicland, seeing spaces, and design studio.” This work is published from: United States.

http://vitor.io/on-dynamicland

@wwj718

**Comment by wangshub** [comment]
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by wwj718** [comment]
@wangshub  cool
