### ISSUE TITLE
关于TWO BIG SCHOOLS OF OBJECT-ORIENTED PROGRAMMING翻译的一点讨论

### ISSUE THREAD

**Issue by hidaris** [Scratch3Lab/codelab-mindstorms#8]
http://stereobooster.github.io/two-big-schools-of-object-oriented-programming

“Messages from actor model are not the same messages from Kay's OOP. But both concept share idea of communication via messages

来自演员模型的消息与 Kay 的 OOP 不同。但这两个概念都通过消息分享了沟通的想法。”

--------
@AngelKitty 感觉这里将actor model译为演员模型有些奇怪，我第一眼没反映过来，查了下常用的翻译是 [角色模型](https://zh.wikipedia.org/wiki/%E8%A7%92%E8%89%B2%E6%A8%A1%E5%9E%8B)，是否可以在一些术语翻译后加上原词汇，类似于演员模型（actor model）呢？

**Comment by AngelKitty** [comment]
@hidaris 啊，您提醒的很对，我觉得可以，有些词汇在翻译上确实很纠结，翻译过程中我也百思不得其解，谢谢您的指导。

**Comment by hidaris** [comment]
@AngelKitty 太客气了，术语方面的翻译确实容易纠结，[哥德尔、艾舍尔、巴赫](https://book.douban.com/subject/1291204/) 一书中“译校者的话”小节，对翻译的信雅达问题进行了很好的讨论，非常值得一读。

**Comment by AngelKitty** [comment]
@hidaris 好滴好滴，有时间我一定会拜读，谢谢您的宝贵建议
