### ISSUE TITLE
关于School的翻译

### ISSUE THREAD

**Issue by wwj718** [Scratch3Lab/codelab-mindstorms#9]
@AngelKitty 

School 翻译“流派”是否会更合适些，比如，  Old School 是老派的意思。

**Comment by AngelKitty** [comment]
@wwj718 这一点我也纠结了很久，具体关于school的定义，我对西方的一些历史了解的不是很多，但是我就想可能是各大学派啥的，流派啊，门派啊啥的觉得可能比较偏向中国化(对这块我不是很了解，所以很乐意接受大家所给出的建议)，非常谢谢您的指出。
